# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# The SBOM tasks have been removed because they are not required for the unofficial template.
# You can manually enable SBOM in the unofficial template if needed, othewise its automatically enabled when using official template. https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sbom
# This pipeline will be extended to the MicroBuild template
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: Nuget packages' in the templateContext section.
trigger: none
schedules:
- cron: "0 0 14 * *"
  branches:
    include:
    - main
  always: true
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
name: $(Date:yyyyMMdd).$(Rev:r)
parameters:
- name: SkipAzureAppConfigProj
  type: boolean
  default: false
- name: SkipAzureProj
  type: boolean
  default: false
- name: SkipEnvironmentProj
  type: boolean
  default: false
- name: SkipJsonProj
  type: boolean
  default: false
- name: SkipKeyPerFileProj
  type: boolean
  default: false
- name: SkipUserSecretsProj
  type: boolean
  default: false
variables:
  TeamName: Asp.Net
  EnableNuGetPackageRestore: true
  SkipPackageRestore: false
  SkipAzureAppConfigProj: ${{ parameters.SkipAzureAppConfigProj }}
  SkipAzureProj:  ${{ parameters.SkipAzureProj }}
  SkipEnvironmentProj:  ${{ parameters.SkipEnvironmentProj }}
  SkipJsonProj:  ${{ parameters.SkipJsonProj }}
  SkipKeyPerFileProj:  ${{ parameters.SkipKeyPerFileProj }}
  SkipUserSecretsProj:  ${{ parameters.SkipUserSecretsProj }}
  # Define these at 'Queue Run...' time to enable full Azure-based tests
  # Microsoft.Configuration.ConfigurationBuilders.Test.AKV.Common: ''
  # Microsoft.Configuration.ConfigurationBuilders.Test.AKV.Custom: ''
  # Microsoft.Configuration.ConfigurationBuilders.Test.AzConfig.Common: ''
  # Microsoft.Configuration.ConfigurationBuilders.Test.AzConfig.Common: ''
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      policheck:
        enable: true
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Phase 1
        timeoutInMinutes: 120
        cancelTimeoutInMinutes: 1
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          mb:
            signing:
              enabled: true
              signType: test
              zipSources: false
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: Nuget packages'
            artifactName: Nuget packages
            targetPath: $(Build.SourcesDirectory)\.binaries\Packages\Release
            sbomEnabled: true
            sbomBuildDropPath: $(Build.SourcesDirectory)\.binaries\Packages\Release
            sbomBuildComponentPath: $(Build.SourcesDirectory)\.binaries\Packages\Release
            sbomPackageName: Microsoft.Configuration.ConfigurationBuilders
            # sbomPackageVersion: $(NugetPackageVersion)
            sbomValidate: true
        steps:
        - checkout: self
          clean: true
          fetchTags: true
          persistCredentials: True
        - task: NuGetToolInstaller@0
          displayName: Use NuGet 5.4.0
          inputs:
            versionSpec: 5.4.0
            checkLatest: true
        - task: NuGetCommand@2
          displayName: NuGet custom
          inputs:
            command: custom
            arguments: install MicroBuild.Core -version 0.3.0 -OutputDirectory .\packages -source https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json
        - task: NuGetCommand@2
          displayName: NuGet restore
          inputs:
            solution: MicrosoftConfigurationBuilders.sln
        - task: MSBuild@1
          displayName: Build solution MicrosoftConfigurationBuilders.msbuild
          inputs:
            solution: MicrosoftConfigurationBuilders.msbuild
            msbuildVersion: 17.0
            msbuildArchitecture: x64
            configuration: Release
            msbuildArguments: /p:GitCommit=$(Build.SourceVersion) /p:GitCommitLink="https://github.com/aspnet/MicrosoftConfigurationBuilders/commit/$(Build.SourceVersion)" /p:SignType=real /p:SignAssembly=true /p:SkipAzureAppConfigProj=$(SkipAzureAppConfigProj) /p:SkipAzureProj=$(SkipAzureProj) /p:SkipEnvironmentProj=$(SkipEnvironmentProj) /p:SkipJsonProj=$(SkipJsonProj) /p:SkipKeyPerFileProj=$(SkipKeyPerFileProj) /p:SkipPackageRestore=$(SkipPackageRestore) /p:SkipUserSecretsProj=$(SkipUserSecretsProj) /verbosity:n
            clean: true
            createLogFile: true
            logFileVerbosity: detailed
          timeoutInMinutes: 120
        - task: CopyFiles@2
          displayName: Stage dll's for verification
          inputs:
            SourceFolder: $(Build.SourcesDirectory)\.binaries\bin\Release
            Contents: Microsoft.Configuration.ConfigurationBuilders.*.dll
            TargetFolder: $(Build.SourcesDirectory)\.binaries\verify\dlls
            CleanTargetFolder: true
            OverWrite: true
        - task: CopyFiles@2
          displayName: Stage nupkg's for verification
          inputs:
            SourceFolder: $(Build.SourcesDirectory)\.binaries\Packages\Release
            Contents: |
              Microsoft.Configuration.ConfigurationBuilders.*.nupkg
              !*.symbols.nupkg
            TargetFolder: $(Build.SourcesDirectory)\.binaries\verify\packages
            CleanTargetFolder: true
            OverWrite: true
        - task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@1
          displayName: Verify Signed Binaries
          inputs:
            TargetFolder: $(Build.SourcesDirectory)\.binaries\verify\dlls
            ExcludeFolders: .git MicroBuild apiscan
        - task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@1
          displayName: Verify Signed Packages
          inputs:
            TargetFolder: $(Build.SourcesDirectory)\.binaries\verify\packages
            WhiteListPathForCerts: tools/.verif.whitelist
            ExcludeFolders: .git MicroBuild decomp *.xml
        # Following article on https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
        # No longer need the old format, and following guideline to use (ApiScanClientId)
        - task: APIScan@2
          displayName: Run APIScan
          inputs:
            softwareFolder: '$(Build.SourcesDirectory)\.binaries\verify\dlls'
            softwareName: 'Microsoft.Configuration.ConfigurationBuilders.*'
            softwareVersionNum: '*'
            softwareBuildNum: '$(Build.BuildId)'
            symbolsFolder: '$(Build.SourcesDirectory)\.binaries\bin\Release;SRV*http://symweb'
            verbosityLevel: 'none'
          env:
            AzureServicesAuthConnectionString: RunAs=App;AppId=$(ApiScanClientId)